Prepare data from Predict Students' Dropout and Academic Success
================================================================
https://archive.ics.uci.edu/dataset/697/predict+students+dropout+and+academic+success

Early prediction of student's performance in higher education: a case study
http://www.worldcist.org/2021/
By Mónica V. Martins, Daniel Tolledo, Jorge Machado, Luís M. T. Baptista, and Valentim Realinho. 2021

Published in Trends and Applications in Information Systems and Technologies

In [ ]:
import os
from dotenv import load_dotenv
import pandas as pd
import mltable

from azure.ai.ml import MLClient
from azure.identity import DefaultAzureCredential
from azure.ai.ml.entities import Data
from azure.ai.ml.constants import AssetTypes
#from azureml.core import Workspace, Dataset <-sdk1

import mltable
from mltable import MLTableHeaders, MLTableFileEncoding, DataType

In [ ]:
load_dotenv()
SUBSCRIPTION_ID = os.environ.get("SUBSCRIPTION_ID")
RESOURCE_GROUP = os.environ.get("RESOURCE_GROUP")
AML_WORKSPACE_NAME = os.environ.get("AML_WORKSPACE_NAME")
print("AML_WORKSPACE_NAME:", AML_WORKSPACE_NAME)

credential = DefaultAzureCredential()
ml_client = MLClient(credential=credential, subscription_id=SUBSCRIPTION_ID, resource_group_name=RESOURCE_GROUP, workspace_name=AML_WORKSPACE_NAME, )

In [ ]:
def create_folder_if_not_exists(folder_path):
    """
    Creates a folder if it doesn't exist.

    Args:
        folder_path (str): The path to the folder.

    Returns:
        None
    """
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)
        print(f"Folder '{folder_path}' created successfully.")
    else:
        print(f"Folder '{folder_path}' already exists.")

Data

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Load the CSV file
data = pd.read_csv('../../../demo_data/academic_sucess.csv')
data['binary_target'] = data['Target'].apply(lambda x: 'Dropout' if x == 'Dropout' else 'Graduated/Still Enrolled')

"""
data['marital_status'] = data['Marital_status'].replace({1: "1 single", 2: "2 married", 3: "3 widower", 4: "4 divorced", 5: "5 facto union", 6: "6 legally separated"})
data.drop(columns=['Marital_status'], inplace=True)
"""
"""
data['application_mode'] = data['Application_mode'].replace({
    1: "1 - 1st phase - general contingent",
    2: "2 - Ordinance No. 612/93",
    5: "5 - 1st phase - special contingent (Azores Island)",
    7: "7 - Holders of other higher courses",
    10: "10 - Ordinance No. 854-B/99",
    15: "15 - International student (bachelor)",
    16: "16 - 1st phase - special contingent (Madeira Island)",
    17: "17 - 2nd phase - general contingent",
    18: "18 - 3rd phase - general contingent",
    26: "26 - Ordinance No. 533-A/99, item b2) (Different Plan)",
    27: "27 - Ordinance No. 533-A/99, item b3 (Other Institution)",
    39: "39 - Over 23 years old",
    42: "42 - Transfer",
    43: "43 - Change of course",
    44: "44 - Technological specialization diploma holders",
    51: "51 - Change of institution/course",
    53: "53 - Short cycle diploma holders",
    57: "57 - Change of institution/course (International)"})
data.drop(columns=['Application_mode'], inplace=True)

data['course'] = data['Course'].replace({
    33: "33 - Biofuel Production Technologies",
    171: "171 - Animation and Multimedia Design",
    8014: "8014 - Social Service (evening attendance)",
    9003: "9003 - Agronomy",
    9070: "9070 - Communication Design 9085 - Veterinary Nursing",
    9119: "9119 - Informatics Engineering",
    9130: "9130 - Equinculture",
    9147: "9147 - Management",
    9238: "9238 - Social Service",
    9254: "9254 - Tourism",
    9500: "9500 - Nursing",
    9556: "9556 - Oral Hygiene",
    9670: "9670 - Advertising and Marketing Management",
    9773: "9773 - Journalism and Communication",
    9853: "9853 - Basic Education",
    9991: "9991 - Management (evening attendance)"})
data.drop(columns=['Course'], inplace=True)

data['daytime_evening_attendance'] = data['Daytime_evening_attendance'].replace({0: "0 evening", 1: "1 daytime"})
data.drop(columns=['Daytime_evening_attendance'], inplace=True)

data['previous_qualification'] = data['Previous_qualification'].replace({
    1: "1 - Secondary education",
    2: "2 - Higher education - bachelor's degree",
    3: "3 - Higher education - degree",
    4: "4 - Higher education - master's",
    5: "5 - Higher education - doctorate",
    6: "6 - Frequency of higher education",
    9: "9 - 12th year of schooling - not completed",
    10: "10 - 11th year of schooling - not completed",
    12: "12 - Other - 11th year of schooling",
    14: "14 - 10th year of schooling",
    15: "15 - 10th year of schooling - not completed",
    19: "19 - Basic education 3rd cycle (9th/10th/11th year) or equiv.",
    38: "38 - Basic education 2nd cycle (6th/7th/8th year) or equiv.",
    39: "39 - Technological specialization course",
    40: "40 - Higher education - degree (1st cycle)",
    42: "42 - Professional higher technical course",
    43: "43 - Higher education - master (2nd cycle)"})
data.drop(columns=['Previous_qualification'], inplace=True)

data['nacionality'] = data['Nacionality'].replace({
    1: "1 - Portuguese",
    2: "2 - German",
    6: "6 - Spanish",
    11: "11 - Italian",
    13: "13 - Dutch",
    14: "14 - English",
    17: "17 - Lithuanian",
    21: "21 - Angolan",
    22: "22 - Cape Verdean",
    24: "24 - Guinean",
    25: "25 - Mozambican",
    26: "26 - Santomean",
    32: "32 - Turkish",
    41: "41 - Brazilian",
    62: "62 - Romanian",
    100: "100 - Moldova (Republic of)",
    101: "101 - Mexican",
    103: "103 - Ukrainian",
    105: "105 - Russian",
    108: "108 - Cuban",
    109: "109 - Colombian"})
data.drop(columns=['Nacionality'], inplace=True)

data['mother_qualification'] = data['Mother_qualification'].replace({
    0: "NA",
    1: "Secondary education",
    2: "Higher education - bachelor's degree",
    3: "Higher education - degree",
    4: "Higher education - master's",
    5: "Higher education - doctorate",
    6: "Frequency of higher education",
    9: "not completed- 12th year of schooling",
    10: "not completed- 11th year of schooling",
    12: "Other - 11th year of schooling",
    14: "schooling - 10th year",
    15: "schooling - 10th year - not completed",
    19: "Basic education 3rd cycle (9th/10th/11th year) or equiv.",
    38: "Basic education 2nd cycle (6th/7th/8th year) or equiv.",
    39: "Technological specialization course",
    40: "Higher education - degree (1st cycle)",
    42: "Professional higher technical course",
    43: "Higher education - master (2nd cycle)"})
data.drop(columns=['Mother_qualification'], inplace=True)

data['father_qualification'] = data['Father_qualification'].replace({
    0: "NA",
    1: "Secondary education",
    2: "Higher education - bachelor's degree",
    3: "Higher education - degree",
    4: "Higher education - master's",
    5: "Higher education - doctorate",
    6: "Frequency of higher education",
    9: "not completed- 12th year of schooling",
    10: "not completed- 11th year of schooling",
    12: "Other - 11th year of schooling",
    14: "schooling - 10th year",
    15: "schooling - not completed - 10th year",
    19: "Basic education 3rd cycle (9th/10th/11th year) or equiv.",
    38: "Basic education 2nd cycle (6th/7th/8th year) or equiv.",
    39: "Technological specialization course",
    40: "Higher education - degree (1st cycle)",
    42: "Professional higher technical course",
    43: "Higher education - master (2nd cycle)"})
data.drop(columns=['Father_qualification'], inplace=True)

data['mother_occupation'] = data['Mother_occupation'].replace({
    0: "Student",
    1: "Representatives of the Legislative Power and Executive Bodies, Directors, Directors and Executive Managers",
    2: "Specialists in Intellectual and Scientific Activities",
    3: "Intermediate Level Technicians and Professions",
    4: "Administrative staff",
    5: "Personal Services, Security and Safety Workers and Sellers",
    6: "Farmers and Skilled Workers in Agriculture, Fisheries and Forestry",
    7: "Skilled Workers in Industry, Construction and Craftsmen",
    8: "Installation and Machine Operators and Assembly Workers",
    9: "Unskilled Workers",
    10: "Armed Forces Professions",
    90: "Other Situation",
    99: "(blank)",
    101: "Armed Forces Officers",
    102: "Armed Forces Sergeants",
    103: "Other Armed Forces personnel",
    112: "Directors of administrative and commercial services",
    114: "Hotel, catering, trade and other services directors",
    121: "Specialists in the physical sciences, mathematics, engineering and related techniques",
    122: "Health professionals",
    123: "teachers",
    124: "Specialists in finance, accounting, administrative organization, public and commercial relations",
    131: "Intermediate level science and engineering technicians and professions",
    132: "Technicians and professionals, of intermediate level of health",
    134: "Intermediate level technicians from legal, social, sports, cultural and similar services",
    135: "Information and communication technology technicians",
    141: "Office workers, secretaries in general and data processing operators",
    143: "Data, accounting, statistical, financial services and registry-related operators",
    144: "Other administrative support staff",
    151: "personal service workers",
    152: "sellers",
    153: "Personal care workers and the like",
    154: "Protection and security services personnel",
    161: "Market-oriented farmers and skilled agricultural and animal production workers",
    163: "Farmers, livestock keepers, fishermen, hunters and gatherers, subsistence",
    171: "Skilled construction workers and the like, except electricians",
    172: "Skilled workers in metallurgy, metalworking and similar",
    174: "Skilled workers in electricity and electronics",
    175: "Workers in food processing, woodworking, clothing and other industries and crafts",
    181: "Fixed plant and machine operators",
    182: "assembly workers",
    183: "Vehicle drivers and mobile equipment operators",
    192: "Unskilled workers in agriculture, animal production, fisheries and forestry",
    193: "Unskilled workers in extractive industry, construction, manufacturing and transport",
    194: "Meal preparation assistants",
    195: "Street vendors (except food) and street service providers"})
data.drop(columns=['Mother_occupation'], inplace=True)

data['father_occupation'] = data['Father_occupation'].replace({
    0: "Student",
    1: "Representatives of the Legislative Power and Executive Bodies, Directors, Directors and Executive Managers",
    2: "Specialists in Intellectual and Scientific Activities",
    3: "Intermediate Level Technicians and Professions",
    4: "Administrative staff",
    5: "Personal Services, Security and Safety Workers and Sellers",
    6: "Farmers and Skilled Workers in Agriculture, Fisheries and Forestry",
    7: "Skilled Workers in Industry, Construction and Craftsmen",
    8: "Installation and Machine Operators and Assembly Workers",
    9: "Unskilled Workers",
    10: "Armed Forces Professions",
    90: "Other Situation",
    99: "(blank)",
    101: "Armed Forces Officers",
    102: "Armed Forces Sergeants",
    103: "Other Armed Forces personnel",
    112: "Directors of administrative and commercial services",
    114: "Hotel, catering, trade and other services directors",
    121: "Specialists in the physical sciences, mathematics, engineering and related techniques",
    122: "Health professionals",
    123: "teachers",
    124: "Specialists in finance, accounting, administrative organization, public and commercial relations",
    131: "Intermediate level science and engineering technicians and professions",
    132: "Technicians and professionals, of intermediate level of health",
    134: "Intermediate level technicians from legal, social, sports, cultural and similar services",
    135: "Information and communication technology technicians",
    141: "Office workers, secretaries in general and data processing operators",
    143: "Data, accounting, statistical, financial services and registry-related operators",
    144: "Other administrative support staff",
    151: "personal service workers",
    152: "sellers",
    153: "Personal care workers and the like",
    154: "Protection and security services personnel",
    161: "Market-oriented farmers and skilled agricultural and animal production workers",
    163: "Farmers, livestock keepers, fishermen, hunters and gatherers, subsistence",
    171: "Skilled construction workers and the like, except electricians",
    172: "Skilled workers in metallurgy, metalworking and similar",
    174: "Skilled workers in electricity and electronics",
    175: "Workers in food processing, woodworking, clothing and other industries and crafts",
    181: "Fixed plant and machine operators",
    182: "assembly workers",
    183: "Vehicle drivers and mobile equipment operators",
    192: "Unskilled workers in agriculture, animal production, fisheries and forestry",
    193: "Unskilled workers in extractive industry, construction, manufacturing and transport",
    194: "Meal preparation assistants",
    195: "Street vendors (except food) and street service providers"})

data.drop(columns=['Father_occupation'], inplace=True)
"""
"""
data['displaced'] = data['Displaced'].replace({0: "No", 1: "Yes"})
data.drop(columns=['Displaced'], inplace=True)

data['educational_special_needs'] = data['Educational_special_needs'].replace({0: "No", 1: "Yes"})
data.drop(columns=['Educational_special_needs'], inplace=True)

data['debtor'] = data['Debtor'].replace({0: "No", 1: "Yes"})
data.drop(columns=['Debtor'], inplace=True)

data['tuition_fees_up_to_date'] = data['Tuition_fees_up_to_date'].replace({0: "No", 1: "Yes"})
data.drop(columns=['Tuition_fees_up_to_date'], inplace=True)

data['gender'] = data['Gender'].replace({0: "Female", 1: "Male"})
data.drop(columns=['Gender'], inplace=True)

data['scholarship_holder'] = data['Scholarship_holder'].replace({0: "No", 1: "Yes"})
data.drop(columns=['Scholarship_holder'], inplace=True)

data['international'] = data['International'].replace({0: "No", 1: "Yes"})
data.drop(columns=['International'], inplace=True)

"""

display(data.head())

#keep a subset of the variables
#data=data[["gender","marital_status", "displaced", "educational_special_needs", "debtor", "tuition_fees_up_to_date", "scholarship_holder", "international", "Daytime_evening_attendance","Unemployment_rate","Inflation_rate","GDP","binary_target"]]
data=data[["Gender","Marital_status", "Displaced", "Educational_special_needs", "Debtor", "Tuition_fees_up_to_date", "Scholarship_holder", "International", "Daytime_evening_attendance","Unemployment_rate","Inflation_rate","GDP","binary_target"]]

# Split the data into train and test sets
train_df, test_df = train_test_split(data, test_size=0.3, random_state=42)

# Print the shapes of the train and test sets
print("Train set shape:", train_df.shape)
print("Test set shape:", test_df.shape)

In [ ]:
#train_df=train_df[["Target","binary_target"]]

print("writting to csv")
create_folder_if_not_exists('../../../demo_data/train_csv/')
train_df.to_csv('../../../demo_data/train_csv/train_csv.csv', index=False)
create_folder_if_not_exists('../../../demo_data/test_csv/')
test_df.to_csv('../../../demo_data/test_csv/test_csv.csv', index=False)

In [ ]:
from azureml.core import Workspace
ws = Workspace.from_config()
datastore = ws.get_default_datastore()

datastore.upload_files(files=["../../../demo_data/train_csv/train_csv.csv"],
                       target_path="/csv/train_csv.csv",
                       overwrite=True)

datastore.upload_files(files=["../../../demo_data/test_csv/test_csv.csv"],
                       target_path="/csv/test_csv.csv",
                       overwrite=True)

In [ ]:
#The compoenents expect mltalbes so need firt to save to either csv or parquet
print("creating mltables")
#import mltable
#from mltable import MLTableHeaders, MLTableFileEncoding, DataType
#train_paths = [{"file": "../../../demo_data/train_csv/train_csv.csv"}]
#train_paths = [{"file": "../../../demo_data/train.parquet"}]
train_paths = [{"file": "azureml://subscriptions/e02ff02a-3d3d-4fa7-828d-54c7d1f4899f/resourcegroups/aauki_eli_demos/workspaces/aauki_eli_demos_amlws01/datastores/workspaceblobstore/paths/csv/train_csv.csv/train_csv.csv"}]
train_mltable = mltable.from_delimited_files(
    paths=train_paths,
    delimiter=",",
    header=MLTableHeaders.all_files_same_headers,
    infer_column_types=True,
    include_path_column=False,
    encoding=MLTableFileEncoding.utf8,
)

#train_mltable = train_mltable.convert_column_types(data_types)
train_mltable.show(5)

create_folder_if_not_exists('../../../demo_data/train_mltalbe/')
train_mltable.save("../../../demo_data/train_mltalbe")

In [ ]:
#test_paths = [{"file": "../../../demo_data/test_csv/test_csv.csv"}]
#test_paths = [{"file": "../../../demo_data/test.parquet"}]
test_paths = [{"file": "azureml://subscriptions/e02ff02a-3d3d-4fa7-828d-54c7d1f4899f/resourcegroups/aauki_eli_demos/workspaces/aauki_eli_demos_amlws01/datastores/workspaceblobstore/paths/csv/test_csv.csv/test_csv.csv"}]
test_mltable = mltable.from_delimited_files(
    paths=test_paths,
    delimiter=",",
    header=MLTableHeaders.all_files_same_headers,
    infer_column_types=True,
    include_path_column=False,
    encoding=MLTableFileEncoding.utf8,
)

#test_mltable = test_mltable.convert_column_types(data_types)
test_mltable.show(5)

create_folder_if_not_exists('../../../demo_data/test_mltalbe/')
test_mltable.save("../../../demo_data/test_mltalbe")

In [ ]:

print("train data-asset")
train_data = Data(
        path="../../../demo_data/train_mltalbe/",
        type=AssetTypes.MLTABLE,
        description="academic_sucess_train",
        name="academic_sucess_train_mltable",
        version="17",
    )
ml_client.data.create_or_update(train_data)

In [ ]:
print("test data-asset")
test_data = Data(
    path="../../../demo_data/test_mltalbe/",
    type="mltable",
    description="academic_sucess_test",
    name="academic_sucess_test_mltable",
    version="17",
)
ml_client.data.create_or_update(test_data)